### ISSUE TITLE
Create folder structure

### ISSUE THREAD

**Issue by raman-m** [fedotkin/dotnet#1]
Create folder structure for the book inside of 'dotnet' repository.

1. Create the dotnet/**trey-nash** folder
2. Create README.md file. Example: [README.md](https://github.com/raman-m/microservices-quick-start#readme)
3. Create folders for each book's chapter like this: '**chapter5**' for the "Interfaces and Contracts" chapter. There will be 17 folders in total. Note: Each chapter's folder should contain readme-file with chapter name & description.

Use chapter titles from the list below 👇 
**List of chapters in English**: [Table of contents](https://link.springer.com/book/10.1007/978-1-4302-2538-6#toc)
1. Chapter 1: C# Preview
2. Chapter 2: C# and the CLR
3. Chapter 3: C# Syntax Overview
4. Chapter 4: Classes, Structs, and Objects
5. Chapter 5: Interfaces and Contracts
6. Chapter 6: Overloading Operators
7. Chapter 7: Exception Handling and Exception Safety
8. Chapter 8: Working with Strings
9. Chapter 9: Arrays, Collection Types, and Iterators
10. Chapter 10: Delegates, Anonymous Functions, and Events
11. Chapter 11: Generics
12. Chapter 12: Threading in C#
13. Chapter 13: In Search of C# Canonical Forms
14. Chaper 14: Extension Methods
15. Chaper 15: Lambda Expressions
16. Chaper 16: LINQ: Language Integrated Query
17. Chaper 17: Dynamic Types

**Comment by raman-m** [comment]
Create folder structure for the book inside of 'dotnet' repository.

1. Create the dotnet/**trey-nash** folder

**Comment by AlexeiFedotkin** [comment]
**trey-nash** folder and **README.md** file were created

**Comment by raman-m** [comment]
You have to create a puul request first to close the issue!

**Comment by raman-m** [comment]
Please, work on the point 3.
