### ISSUE TITLE
HackerRank | Algorithms > Strings > Two Characters

### ISSUE THREAD

**Issue by fedotkin** [fedotkin/dotnet#100]
HackerRank challenge: [Two Characters](https://www.hackerrank.com/challenges/two-characters/problem)
Domain: [Algorithms](https://www.hackerrank.com/domains/algorithms)
Subdomain: [Strings](https://www.hackerrank.com/domains/algorithms/strings)
Difficulty: Easy

**Comment by raman-m** [comment]
Сотачка! 💯 😃
