### ISSUE TITLE
Polish README

### ISSUE THREAD

**Issue by raman-m** [fedotkin/dotnet#16]
There are some formatting issues and logical mistakes which are made in [README.md](https://github.com/fedotkin/dotnet/blob/master/README.md) of the main folder.
So, the README.md should be polished to the state without any issues. The README must be functional, nice and efficient.

**1st issue**: No References [heading](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#headings)
![image](https://user-images.githubusercontent.com/10501504/203296691-8f0f4086-f255-4c13-9edc-3cc1fdcd9518.png)
The current footnotes are not structured well. There is NO **References** heading. Also the text is strange and it's ugly: it contains English grammar mistakes. The text doesn't say about actual reference/link. The text must contain the title of the referenced docs/webpage. The example: https://github.com/fedotkin/dotnet/tree/trey-nash/trey-nash/5-interfaces-and-contracts, see at the bottom.

**2nd issue**: A number of text formatting issues in the "[What is .NET Framework? A software development framework.](https://dotnet.microsoft.com/en-us/learn/dotnet/what-is-dotnet-framework)" referencing.
![image](https://user-images.githubusercontent.com/10501504/203301933-62560f1e-99dd-4040-b503-012d20c25a5c.png)
So, the formatting errors are highlighted.

**3rd issue**: A number of text formatting issues in the "[A tour of C# - Overview | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/)" referencing.
![image](https://user-images.githubusercontent.com/10501504/203304078-4b61074b-c713-42f6-b30d-f0676f1ec72d.png)
Formatting errors are highlighted.

**4th issue**. Add [C# docs - get started, tutorials, reference. | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/csharp/) reference too as the main reference to **C#** heading. This reference should be cited in the footnotes also.

**Comment by raman-m** [comment]
**4th issue**. Add [C# docs - get started, tutorials, reference. | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/csharp/) reference too as the main reference to C# heading. This reference should be cited in the footnotes also.

**Comment by raman-m** [comment]
I see that the hotfix has been merged to master. But... You have to deliver this hotfix to [trey-nash](https://github.com/fedotkin/dotnet/tree/trey-nash) too!

**Comment by fedotkin** [comment]
need help (possibly at a meeting)

**Comment by raman-m** [comment]
Done by #23.
The hotfix has been delivered.
