### ISSUE TITLE
TODO: Define root namespace explicitly in the project.

### ISSUE THREAD

**Issue by fedotkin** [fedotkin/dotnet#32]
Program.cs

**Comment by raman-m** [comment]
This task is obsolete, and it is done by PR #34 .
Commit: [Define root namespace as Fedotkin.Dotnet.TreyNash](https://github.com/fedotkin/dotnet/commit/f97e305a28499a55d227756df9433ea085044ae2)
Line: [trey-nash/ChapterExercises.csproj, Line 8](https://github.com/fedotkin/dotnet/blame/trey-nash/trey-nash/ChapterExercises.csproj#L8)
