### ISSUE TITLE
TreyNash | Chapter 2 | Exercise 1: Assemblies and the Assembly Loader

### ISSUE THREAD

**Issue by raman-m** [fedotkin/dotnet#37]
# Chapter 2. [Exercise 1](../blob/trey-nash-dev/trey-nash/2-c%23-and-the-clr/Exercise1.md)
## Assemblies and the Assembly Loader
You need to practice with assemblies, the basic work with assemblies is described in [Chapter 2](../blob/trey-nash-dev/trey-nash/2-c%23-and-the-clr/README.md).

So, you will create some Library project. In Console application you need to load compiled DLL-assembly, discover all types defined there, and print all definitions of all types to console window.

Note, to do the task, you have to use the `System.Assembly` class, and other `System.Reflection` classes and functionality, like the `Object.GetType()` method, `typeof()` operator and the `Type` class functionality.

**Implementation path:**
1. Create Calculator project (Library)
2. Define `Calculator` class with 4 methods **Add**, **Subtract**, **Multiply** and **Divide**.
3. Create Console project. Do not make reference to Calculator project!
4. Load assembly of Calculator DLL via `Assembly.Load` method or `AppDomain.CurrentDomain.Load` one.
5. Get all types which defined in the Calculator assembly.
6. Get all methods which defined in a class you discover.
7. Print all types and its methods being discovered to the console.

**Comment by fedotkin** [comment]
Implemented by #47
