### ISSUE TITLE
HackerRank | Algorithms > Implementation > Cats and a Mouse

### ISSUE THREAD

**Issue by raman-m** [fedotkin/dotnet#39]
HackerRank challenge: [Cats and a Mouse](https://www.hackerrank.com/challenges/cats-and-a-mouse/problem)
Domain: [Algorithms](https://www.hackerrank.com/domains/algorithms)
Subdomain: [Implementation](https://www.hackerrank.com/domains/algorithms/implementation)
Difficulty: Easy

The path in this repo should be "../hackerrank/"

**Comment by raman-m** [comment]
⚠️  I advise you write TTD unit tests at least for cases of Example and Sample!
Unit tests for the `Solution.catAndMouse()` method.

**Comment by fedotkin** [comment]
Implemented by #46
