### ISSUE TITLE
HackerRank | Algorithms > Warmup > Compare the Triplets

### ISSUE THREAD

**Issue by fedotkin** [fedotkin/dotnet#84]
HackerRank challenge: [Compare the Triplets](https://www.hackerrank.com/challenges/compare-the-triplets/problem)
Domain: [Algorithms](https://www.hackerrank.com/domains/algorithms)
Subdomain: [Warmup](https://www.hackerrank.com/domains/algorithms/warmup)
Difficulty: Easy

**Comment by raman-m** [comment]
Джун пачаў варушыцца! 😮 Напэўна восень прыйшла і холадна на вуліцы. 😄

**Comment by fedotkin** [comment]
Implemented by #85
