### ISSUE TITLE
HackerRank | Algorithms > Implementation > Between Two Sets

### ISSUE THREAD

**Issue by fedotkin** [fedotkin/dotnet#88]
HackerRank challenge: [Between Two Sets](https://www.hackerrank.com/challenges/between-two-sets/problem)
Domain: [Algorithms](https://www.hackerrank.com/domains/algorithms)
Subdomain: [Implementation](https://www.hackerrank.com/domains/algorithms/implementation)
Difficulty: Easy

**Comment by fedotkin** [comment]
Implemented by #89

**Comment by raman-m** [comment]
> @fedotkin commented [on Oct 29](#issuecomment-1784030128)

Не трэба пісаць гэтае паведамленне!
І так зразумела якім пулрэквестам ты закрыў задачу! Вось сістэмнае паведамленне самаго Гітхаба:
> @fedotkin linked a pull request [on Oct 26](#event-10778324897) that will close this issue
