### ISSUE TITLE
HackerRank | Algorithms > Strings > Pangrams

### ISSUE THREAD

**Issue by fedotkin** [fedotkin/dotnet#96]
HackerRank challenge: [Pangrams](https://www.hackerrank.com/challenges/pangrams/problem)
Domain: [Algorithms](https://www.hackerrank.com/domains/algorithms)
Subdomain: [Strings](https://www.hackerrank.com/domains/algorithms/strings)
Difficulty: Easy

**Comment by raman-m** [comment]
Давай джун, пілі код! 😉
